### ISSUE TITLE
WindowsError: [Error 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by heldersepu** [Tribler/tribler#3283]
#### Tribler version/branch+revision: ####
https://github.com/Tribler/tribler/releases/tag/v7.0.0-rc4
Tribler_7.0.0-rc4_x86.exe

#### Operating system and version: ####
Windows 10   Version 1709 

#### Steps to reproduce the behavior: ####
I had a few(6) torrents downloading and it just stopped working with the error below
Restarting Tribler fixed the issue

#### Relevant log file output: ####
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file routing.py, line 99
Traceback (most recent call last):
  File "lib\logging\handlers.py", line 77, in emit
  File "lib\logging\handlers.py", line 142, in doRollover
WindowsError: [Error 32] The process cannot access the file because it is being used by another process
Logged from file routing.py, line 99
Traceback (most recent call last):
  File "lib\logging\handlers.py", line 77, in emit
  File "lib\logging\handlers.py", line 142, in doRollover

**Comment by devos50** [comment]
Thank you for the bug report!

Did you by any change touch or modify the file that stores the Tribler log (usually located in `C:\Users\<yourusername>\AppData\.Tribler`)? Or maybe there's a program interfering with these files?

Since it was solved by a restart and since it's not a critical issue, I suggest we postpone this to the 7.1 release.

**Comment by heldersepu** [comment]
Nope, I haven't modified anything on the `.Tribler` directory.
And it is actually: `C:\Users\<yourusername>\AppData\Roaming\.Tribler`
or using the system variable `%AppData%\.Tribler`

Looking at the console I see that the error still showing just now is every once in awhile

**Comment by devos50** [comment]
@heldersepu ah yeah indeed, it's in the `Roaming` directory.

Does Tribler actually crash when you get this error in your console (with the option to send a crash report to us)?

Could you please help us debugging this error? To provide us with more information, could you, when Tribler crashes again with this error or this error shows in the console, find out which process is using the log file in the `.Tribler` directory? You can do this by following this guide: https://www.techsupportalert.com/content/how-find-out-which-windows-process-using-file.htm

Please let me know if you need more help with this. Any help would be greatly appreciated!

**Comment by heldersepu** [comment]
No, now that you mentioned, it does not crash on the sense ...
The symptoms are:
 - download & upload speeds go to 0 
 - when I try to close the app it stays frozen in the "Shutting down.." screen

**Comment by devos50** [comment]
@heldersepu ah, I'm feeling that the whole state directory is not writable anymore. Could you try to close any background programs that might interfere with other files on the operating system (like virus scanners)?

**Comment by heldersepu** [comment]
Only the tribler.exe shows in the process explorer
![image](https://user-images.githubusercontent.com/545474/33809557-e3d613d6-ddc6-11e7-80ca-032523471372.png)

**Comment by devos50** [comment]
@heldersepu it seems that another PID with ID 2080 is also using these two files. Is there somehow another `tribler.exe` still active in the background?

**Comment by heldersepu** [comment]
Interesting ...
Yes there are two 'tribler.exe' both close when I close the UI and both open when I launch the app.
![image](https://user-images.githubusercontent.com/545474/33809800-9fce5cf8-ddca-11e7-8eab-687e72ba1e60.png)

**Comment by devos50** [comment]
Tribler spawns a subprocess but I’m not sure whether there should be two Tribler.exe instances under the main Tribler.exe. I will discuss this with the team tomorrow. Thank you for your help so far!

**Comment by devos50** [comment]
(Maybe write GUI logs to a different file?)

**Comment by heldersepu** [comment]
Yep that will work, maybe change the log file name to include the PID `os.getpid()`

**Comment by heldersepu** [comment]
Awesome!
Do you guys have a CI environment where I can download the latest installer?

**Comment by devos50** [comment]
@heldersepu sure, you can check out our Jenkins build: https://jenkins.tribler.org/job/Build_Tribler_next/163/

The installers will be available as soon as the build finishes. Thank you for testing!

**Comment by heldersepu** [comment]
Looking good no errors anymore ...
and I see the new log files:

```
Microsoft Windows [Version 10.0.16299.98]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\root\AppData\Roaming\.Tribler\logs>dir
 Volume in drive C has no label.
 Volume Serial Number is A6FE-7BDC

 Directory of C:\Users\root\AppData\Roaming\.Tribler\logs

12/13/2017  09:31 AM    <DIR>          .
12/13/2017  09:31 AM    <DIR>          ..
12/13/2017  09:28 AM                 0 tribler-core-error.log
12/13/2017  09:31 AM           558,908 tribler-core-info.log
12/13/2017  09:28 AM                 0 tribler-gui-error.log
12/13/2017  09:31 AM               587 tribler-gui-info.log
               4 File(s)        559,495 bytes
               2 Dir(s)  40,321,236,992 bytes free

```

**Comment by devos50** [comment]
@heldersepu thanks for testing! If you encounter more issues, please post them so we can look at them.

**Comment by heldersepu** [comment]
My pleasure!
On Jenkins I see you got some failures, it seems to be something on the deployment_tests

**Comment by devos50** [comment]
@heldersepu we know and we will look at it later :)
