### ISSUE TITLE
LaunchManyCore fails to produce notification on torrent completion

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#3719]
If a download takes less than a second to complete, `sesscb_states_callback` fails to produce the notification on torrent finish.
It happens because `new_active_downloads` only gets new entries if their status is `DLSTATUS_DOWNLOADING`:
https://github.com/Tribler/tribler/blob/8981c831c4e4be7871b0b4eb58715107e83d28fb/Tribler/Core/APIImplementation/LaunchManyCore.py#L679-L698

This makes notification fail for corner cases, like unit tests.

**Comment by devos50** [comment]
Nice find! Certainly an edge case. I guess it's not hard to reproduce this with a unit test and fix it? 👍

**Comment by qstokkink** [comment]
Adding the download to `self.previous_active_downloads` in [add()](https://github.com/Tribler/tribler/blob/8981c831c4e4be7871b0b4eb58715107e83d28fb/Tribler/Core/APIImplementation/LaunchManyCore.py#L455) should fix this I think.

**Comment by ichorid** [comment]
After pondering on this for a few hours I can say that it is impossible to fix this problem correctly without refactoring the libtorrent wrapper.

**Comment by qstokkink** [comment]
Related to #3418

**Comment by qstokkink** [comment]
This seems like it will be fixed in #3775, so I will mark this as completed with AllChannel2.0.

**Comment by ichorid** [comment]
@qstokkink, I used a different mechanism there, so it is not fixed. This will be fixed with redesign of Libtorrent wrapper, so it should stay opened as a reminder.

**Comment by devos50** [comment]
@ichorid we addressed this already with the finished callback in the `LibtorrentDownloadImpl` itself right?

**Comment by ichorid** [comment]
Solved by #4090

**Comment by ichorid** [comment]
In fact, this is only solved for GigaChannels, because we now don't rely on triggers, but instead schedule periodic channels DB consistency checks.
