### ISSUE TITLE
[7.5.0-exp1] Name or service not known

### ISSUE THREAD

**Issue by Dmole** [Tribler/tribler#5167]
Traceback (most recent call last):
  File "/home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 114, in on_read_data
RuntimeError: [Errno -2] Name or service not known

Also it's stuck on "Sending..."

**Comment by ichorid** [comment]
If you're on Windows, you can copy-paste the debug console here. It'll say much more in this case.

**Comment by synctext** [comment]
We need a bit more info to start debugging. Can you reproduce this?

**Comment by ichorid** [comment]
Another user reported the same issues and posted a log on the forum. He said that this only happened during the first run of 7.5.0-exp1.
```python
INFO:CrawlRequestCache:Timeout for crawl with id 45811
INFO:TorrentChecker:Selected 17 new torrents to check on tracker: udp://tracker.ccc.de:80
WARNING:TorrentChecker:Got session error for URL udp://tracker.ccc.de:80: Register_task takes a Task or a (coroutine)function as a parameter
ERROR:Session:Got unhandled error: [Errno -2] Name or service not known
INFO:TriblerTunnelCommunity:Removed candidate from candidates dictionary
INFO:TriblerTunnelCommunity:Removed candidate from candidates dictionary
ERROR:root:Traceback (most recent call last):
  File "/home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 114, in on_read_data
RuntimeError: [Errno -2] Name or service not known

INFO:Session:Tribler shutdown state notification:Shutting down Credit Mining...
INFO:CreditMiningManager:Shutting down CreditMiningManager
INFO:Session:Tribler shutdown state notification:Shutting down Torrent Checker...
INFO:Session:Tribler shutdown state notification:Shutting down Gigachannel Manager...
INFO:Session:Tribler shutdown state notification:Shutting down Video Server...
INFO:Session:Tribler shutdown state notification:Shutting down Version Checker...
INFO:Session:Tribler shutdown state notification:Shutting down Resource Monitor...
INFO:Session:Tribler shutdown state notification:Unloading Tunnel Community...
INFO:Socks5Connection:Closing session, reason stopping
INFO:Socks5Connection:Closing session, reason unspecified
INFO:TriblerTunnelCommunity:Destroy_exit_socket 798902237 ('81.171.27.193', 35025)
INFO:TriblerTunnelCommunity:Removing DATA circuit 508549547 unload
INFO:TriblerTunnelCommunity:destroy_circuit 508549547 ('81.171.8.19', 35195)
INFO:Session:Tribler shutdown state notification:Shutting down TrustChain Community...
INFO:Session:Tribler shutdown state notification:Shutting down IPv8...
INFO:Session:Tribler shutdown state notification:Saving configuration...
INFO:Session:Tribler shutdown state notification:Checkpointing Downloads...
INFO:Session:Tribler shutdown state notification:Shutting down Downloads...
INFO:Session:Tribler shutdown state notification:Shutting down Libtorrent Manager...
INFO:Session:Tribler shutdown state notification:Waiting for Libtorrent to finish...
INFO:Session:Tribler shutdown state notification:Shutting down Metadata Store...
INFO:Session:Tribler shutdown state notification:Shutting down API Manager...
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
ERROR:root:No json object could be decoded from data: b'missing version key'
```

**Comment by Dmole** [comment]
No I can't seem to reproduce it (even after resorting an old backup of ~/.Tribler).
Maybe it's intermittent, or related to a slow background upgrade...

**Comment by Dmole** [comment]
But I do have the log;
```

Logger config not found in tribler-gui/tribler_gui/logger.yaml. Using default configs.
INFO:root:__init__()
INFO:root:  self._outSocket.error() = '2'
INFO:root:__init__(): returning
QFont::setPointSize: Point size <= 0 (-1), must be greater than 0
INFO:TriblerGUI:Will connect to events endpoint
INFO:TriblerGUI:Got Tribler core error: 1
INFO:TriblerGUI:Will connect to events endpoint
INFO:TriblerGUI:Got Tribler core error: 1
INFO:TriblerGUI:Will connect to events endpoint
INFO:TriblerGUI:Got Tribler core error: 1
INFO:TriblerGUI:Will connect to events endpoint
INFO:TriblerGUI:Got Tribler core error: 1
INFO:TriblerGUI:Will connect to events endpoint
INFO:TriblerGUI:Got Tribler core error: 1
Logger config not found in tribler-core/tribler_core/logger.yaml. Using default configs.
INFO:Session:Session is using state directory: /home/User/.Tribler/7.5
INFO:RESTManager:Starting REST API on port 8085
INFO:TriblerGUI:Will connect to events endpoint
INFO:root:Generating grammar tables from /usr/share/tribler/lib2to3/Grammar.txt
INFO:root:Generating grammar tables from /usr/share/tribler/lib2to3/PatternGrammar.txt
INFO:RefactoringTool:Skipping optional fixer: buffer
INFO:RefactoringTool:Skipping optional fixer: idioms
INFO:RefactoringTool:Skipping optional fixer: set_literal
INFO:RefactoringTool:Skipping optional fixer: ws_comma
INFO:TrackerManager:No tracker blacklist file found at /home/User/.Tribler/7.5/tracker_blacklist.txt.
INFO:LibtorrentMgr:could not load libtorrent state, got exception: FileNotFoundError(2, 'No such file or directory'). starting from scratch
INFO:DHTDiscoveryCommunity:DHT community initialized (peer mid b'acad090deab24039a4c7682228214175005db2b9')
INFO:TriblerTunnelCommunity:Setting exitnode = 0
ERROR:TriblerTunnelCommunity:Could not retrieve backup exitnode cache, file does not exist!
INFO:DatabaseOrderRepository:Memory order repository used
INFO:DatabaseTransactionRepository:Database transaction repository used
INFO:OrderManager:Market order manager initialized
INFO:TransactionManager:Transaction manager initialized
INFO:MarketCommunity:Market community initialized with mid b'acad090deab24039a4c7682228214175005db2b9'
INFO:PopularityCommunity:Popularity Community initialized (peer mid acad090deab24039a4c7682228214175005db2b9)
ERROR:Session:bitcoinlib library cannot be loaded: No module named 'bitcoinlib'
INFO:CreditMiningManager:Starting CreditMiningManager
INFO:TriblerGUI:Will connect to events endpoint
WARNING:root:Received duplicate Tribler Core started event
INFO:TrustChainCommunity:Requesting crawl of node b'fb7ae571' (blocks 4 to 4) with id 1478
INFO:TrustChainCommunity:Requesting crawl of node b'12823d41' (blocks 3 to 3) with id 44151
INFO:TrustChainCommunity:Requesting crawl of node b'8f844131' (blocks 2 to 2) with id 48620
INFO:TrustChainCommunity:Block validation result <function ValidationResult.partial_next at 0x7fd2e9dc8488>, [], (Block b'586468df' from ...b'fb7ae571':4 links ...b'f79336be':29037 for {b'down': 0, b'total_down': 35473821, b'up': 1060960, b'total_up': 108936302} type b'tribler_bandwidth')
INFO:TrustChainCommunity:Block validation result <function ValidationResult.no_info at 0x7fd2e9dc8598>, [], (Block b'250e633f' from ...b'43eea11c':4 links ...b'fb7ae571':0 for {b'up': 0, b'down': 24944140, b'total_up': 0, b'total_down': 354107905} type b'tribler_bandwidth')
INFO:TrustChainCommunity:Block validation result <function ValidationResult.partial_next at 0x7fd2e9dc8488>, [], (Block b'6203abb5' from ...b'8f844131':2 links ...b'04ee5b27':3685 for {b'down': 0, b'total_down': 0, b'up': 38715924, b'total_up': 77597320} type b'tribler_bandwidth')
INFO:TrustChainCommunity:Block validation result <function ValidationResult.partial_next at 0x7fd2e9dc8488>, [], (Block b'd0d65ccc' from ...b'12823d41':3 links ...b'1e80eeb7':1485 for {b'down': 0, b'total_down': 0, b'up': 1298383, b'total_up': 14396526} type b'tribler_bandwidth')
INFO:TrustChainCommunity:Requesting crawl of node b'103b33af' (blocks 1 to 1) with id 1499
INFO:TrustChainCommunity:Requesting crawl of node b'6a6c3d59' (blocks 3 to 3) with id 27206
INFO:TrustChainCommunity:Block validation result <function ValidationResult.partial_next at 0x7fd2e9dc8488>, [], (Block b'542ba39b' from ...b'6a6c3d59':3 links ...b'9f7a1701':710 for {b'down': 0, b'total_down': 0, b'up': 4103767, b'total_up': 20867820} type b'tribler_bandwidth')
INFO:TrustChainCommunity:Block validation result <function ValidationResult.no_info at 0x7fd2e9dc8598>, [], (Block b'0f31831b' from ...b'a2cccce5':3 links ...b'6a6c3d59':0 for {b'down': 15525581, b'total_down': 172450015, b'up': 0, b'total_up': 0} type b'tribler_bandwidth')
ERROR:LibtorrentDownloadImpl:Resume data failed to save: <class 'tribler_core.exceptions.SaveResumeDataError'>: torrent has no metadata
INFO:TrustChainCommunity:Block validation result <function ValidationResult.partial_next at 0x7fd2e9dc8488>, [], (Block b'0387f19d' from ...b'103b33af':1 links ...b'1999cf35':5219 for {b'down': 0, b'total_down': 0, b'up': 12551113, b'total_up': 12551113} type b'tribler_bandwidth')
INFO:TrustChainCommunity:Requesting crawl of node b'ecb110e9' (blocks 3 to 3) with id 47021
INFO:TrustChainCommunity:Block validation result <function ValidationResult.partial_next at 0x7fd2e9dc8488>, [], (Block b'eca152c5' from ...b'ecb110e9':3 links ...b'1e80eeb7':1448 for {b'down': 0, b'total_down': 0, b'up': 1177995, b'total_up': 309761606} type b'tribler_bandwidth')
INFO:CreditMiningManager:Downloading: 0, Uploading: 0, Stopped: 0
INFO:CreditMiningManager:0 active download(s), 0.000 MB uploaded, 0.000 MB downloaded
INFO:TrustChainCommunity:Requesting crawl of node b'ece911fb' (blocks 2 to 2) with id 28888
INFO:TrustChainCommunity:Block validation result <function ValidationResult.partial_next at 0x7fd2e9dc8488>, [], (Block b'3a906d95' from ...b'ece911fb':2 links ...b'9694b005':375 for {b'down': 0, b'total_down': 31767018, b'up': 52945030, b'total_up': 52945030} type b'tribler_bandwidth')
INFO:TrustChainCommunity:Block validation result <function ValidationResult.no_info at 0x7fd2e9dc8598>, [], (Block b'da04324b' from ...b'35c4ecd3':2 links ...b'ece911fb':0 for {b'up': 0, b'down': 1303609, b'total_up': 0, b'total_down': 8116972} type b'tribler_bandwidth')
INFO:TriblerTunnelCommunity:Removed candidate from candidates dictionary
INFO:TriblerTunnelCommunity:Removed candidate from candidates dictionary
INFO:TriblerTunnelCommunity:Removed candidate from candidates dictionary
INFO:TriblerTunnelCommunity:Removed candidate from candidates dictionary
INFO:TriblerTunnelCommunity:Removed candidate from candidates dictionary
INFO:TriblerTunnelCommunity:Removed candidate from candidates dictionary
INFO:TriblerTunnelCommunity:Removed candidate from candidates dictionary
INFO:TriblerTunnelCommunity:Removed candidate from candidates dictionary
INFO:TriblerTunnelCommunity:Removed candidate from candidates dictionary
INFO:TriblerTunnelCommunity:Removed candidate from candidates dictionary
INFO:TriblerTunnelCommunity:Removed candidate from candidates dictionary
INFO:TriblerTunnelCommunity:Removed candidate from candidates dictionary
INFO:TriblerTunnelCommunity:Removed candidate from candidates dictionary
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
INFO:TrustChainCommunity:Requesting crawl of node b'94bfeef0' (blocks 1 to 1) with id 29748
INFO:TrustChainCommunity:Block validation result <function ValidationResult.partial_next at 0x7fd2e9dc8488>, [], (Block b'791e0d8d' from ...b'94bfeef0':1 links ...b'4a6d5744':120209 for {b'down': 0, b'total_down': 0, b'up': 210036954, b'total_up': 210036954} type b'tribler_bandwidth')
INFO:TrustChainCommunity:Requesting crawl of node b'b86bc3a7' (blocks 11 to 11) with id 19758
INFO:TrustChainCommunity:Requesting crawl of node b'0859676b' (blocks 6 to 6) with id 56002
INFO:TrustChainCommunity:Requesting crawl of node b'cbdf05cc' (blocks 9 to 9) with id 28679
INFO:TrustChainCommunity:Requesting crawl of node b'6b2a7ec4' (blocks 6 to 6) with id 36408
INFO:TrustChainCommunity:Requesting crawl of node b'4f6d47b3' (blocks 3 to 3) with id 1888
INFO:TrustChainCommunity:Requesting crawl of node b'debd1646' (blocks 2 to 2) with id 54842
INFO:TrustChainCommunity:Block validation result <function ValidationResult.partial_next at 0x7fd2e9dc8488>, [], (Block b'0dbb928e' from ...b'b86bc3a7':11 links ...b'd0036190':40 for {b'down': 0, b'total_down': 63281331, b'up': 1946644, b'total_up': 149551701} type b'tribler_bandwidth')
INFO:TrustChainCommunity:Block validation result <function ValidationResult.partial_next at 0x7fd2e9dc8488>, [], (Block b'2367caab' from ...b'58254d95':11 links ...b'b86bc3a7':0 for {b'down': 8356499, b'total_down': 391214372, b'up': 0, b'total_up': 0} type b'tribler_bandwidth')
INFO:TrustChainCommunity:Block validation result <function ValidationResult.partial_next at 0x7fd2e9dc8488>, [], (Block b'764c3bb8' from ...b'6b2a7ec4':6 links ...b'76a507ba':26465 for {b'down': 0, b'total_down': 66689248, b'up': 8890889, b'total_up': 266147184} type b'tribler_bandwidth')
INFO:TrustChainCommunity:Block validation result <function ValidationResult.partial_next at 0x7fd2e9dc8488>, [], (Block b'258e8d26' from ...b'cbdf05cc':9 links ...b'ff4d4595':1339 for {b'down': 0, b'total_down': 29699823, b'up': 91502033, b'total_up': 379419348} type b'tribler_bandwidth')
INFO:TrustChainCommunity:Block validation result <function ValidationResult.partial_next at 0x7fd2e9dc8488>, [], (Block b'3dea900c' from ...b'0859676b':6 links ...b'58cd5a03':24 for {b'down': 0, b'total_down': 0, b'up': 83179872, b'total_up': 168039655} type b'tribler_bandwidth')
INFO:TrustChainCommunity:Block validation result <function ValidationResult.partial_next at 0x7fd2e9dc8488>, [], (Block b'5d0b8d2f' from ...b'4f6d47b3':3 links ...b'b88200fb':8 for {b'down': 0, b'total_down': 21555132, b'up': 29834542, b'total_up': 74760502} type b'tribler_bandwidth')
INFO:TrustChainCommunity:Block validation result <function ValidationResult.partial_next at 0x7fd2e9dc8488>, [], (Block b'ee5a6877' from ...b'debd1646':2 links ...b'25acb686':10 for {b'down': 0, b'total_down': 0, b'up': 1247660, b'total_up': 14336732} type b'tribler_bandwidth')
INFO:TrustChainCommunity:Requesting crawl of node b'0f9398ed' (blocks 1 to 1) with id 23127
INFO:TrustChainCommunity:Block validation result <function ValidationResult.partial_next at 0x7fd2e9dc8488>, [], (Block b'd7b29de0' from ...b'0f9398ed':1 links ...b'61dd4e3d':412239 for {b'up': 5157912, b'down': 0, b'total_up': 5157912, b'total_down': 0} type b'tribler_bandwidth')
INFO:TrustChainCommunity:Requesting crawl of node b'9f8a4be9' (blocks 2 to 2) with id 63378
INFO:TrustChainCommunity:Block validation result <function ValidationResult.partial_next at 0x7fd2e9dc8488>, [], (Block b'a893b220' from ...b'9f8a4be9':2 links ...b'b4e972fa':173 for {b'down': 0, b'total_down': 0, b'up': 114918285, b'total_up': 116199040} type b'tribler_bandwidth')
INFO:TrustChainCommunity:Block validation result <function ValidationResult.partial_next at 0x7fd2e9dc8488>, [], (Block b'6694cc2f' from ...b'200aca18':2 links ...b'9f8a4be9':4 for {b'down': 0, b'total_down': 6222288, b'up': 18666864, b'total_up': 18666864} type b'tribler_bandwidth')
INFO:CreditMiningManager:Downloading: 0, Uploading: 0, Stopped: 0
INFO:CreditMiningManager:0 active download(s), 0.000 MB uploaded, 0.000 MB downloaded
INFO:TrustChainCommunity:Requesting crawl of node b'd28b29d6' (blocks 7 to 7) with id 59587
INFO:TrustChainCommunity:Requesting crawl of node b'5e1e0ae3' (blocks 3 to 3) with id 18809
INFO:TrustChainCommunity:Requesting crawl of node b'6a92804b' (blocks 1 to 1) with id 4340
INFO:TrustChainCommunity:Block validation result <function ValidationResult.partial_next at 0x7fd2e9dc8488>, [], (Block b'85e39b55' from ...b'5e1e0ae3':3 links ...b'5d5ed1b2':18599 for {b'down': 0, b'total_down': 0, b'up': 4684956, b'total_up': 9064554} type b'tribler_bandwidth')
INFO:TrustChainCommunity:Block validation result <function ValidationResult.no_info at 0x7fd2e9dc8598>, [], (Block b'9b3e9dce' from ...b'd0e01ecf':3 links ...b'5e1e0ae3':0 for {b'up': 0, b'down': 43576459, b'total_up': 0, b'total_down': 106649686} type b'tribler_bandwidth')
INFO:TrustChainCommunity:Block validation result <function ValidationResult.partial_next at 0x7fd2e9dc8488>, [], (Block b'497f65ee' from ...b'd28b29d6':7 links ...b'20d3f8e9':1094 for {b'down': 0, b'total_down': 24849912, b'up': 1272258, b'total_up': 100140199} type b'tribler_bandwidth')
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
INFO:CreditMiningManager:Downloading: 0, Uploading: 0, Stopped: 0
INFO:CreditMiningManager:0 active download(s), 0.000 MB uploaded, 0.000 MB downloaded
INFO:CreditMiningManager:Downloading: 0, Uploading: 0, Stopped: 0
INFO:CreditMiningManager:0 active download(s), 0.000 MB uploaded, 0.000 MB downloaded
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
ERROR:Bootstrap:Failed to get DHT response:No nodes found in the routing table
INFO:TorrentChecker:Selected 1 new torrents to check on tracker: udp://fr33domtracker.h33t.com:3310
WARNING:TorrentChecker:Got session error for URL udp://fr33domtracker.h33t.com:3310: Register_task takes a Task or a (coroutine)function as a parameter
ERROR:Session:Got unhandled error: [Errno -2] Name or service not known
ERROR:root:Traceback (most recent call last):
  File "/home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 114, in on_read_data
RuntimeError: [Errno -2] Name or service not known

INFO:Session:Tribler shutdown state notification:Shutting down Credit Mining...
INFO:CreditMiningManager:Shutting down CreditMiningManager
INFO:Session:Tribler shutdown state notification:Shutting down Torrent Checker...
INFO:Session:Tribler shutdown state notification:Shutting down Gigachannel Manager...
INFO:Session:Tribler shutdown state notification:Shutting down Video Server...
INFO:Session:Tribler shutdown state notification:Shutting down Version Checker...
INFO:Session:Tribler shutdown state notification:Shutting down Resource Monitor...
INFO:Session:Tribler shutdown state notification:Unloading Tunnel Community...
INFO:Session:Tribler shutdown state notification:Shutting down TrustChain Community...
INFO:Session:Tribler shutdown state notification:Shutting down IPv8...
INFO:Session:Tribler shutdown state notification:Shutting down Watch Folder...
INFO:Session:Tribler shutdown state notification:Saving configuration...
INFO:Session:Tribler shutdown state notification:Checkpointing Downloads...
INFO:Session:Tribler shutdown state notification:Shutting down Downloads...
INFO:Session:Tribler shutdown state notification:Shutting down Libtorrent Manager...
INFO:Session:Tribler shutdown state notification:Waiting for Libtorrent to finish...
INFO:Session:Tribler shutdown state notification:Shutting down Metadata Store...
INFO:Session:Tribler shutdown state notification:Shutting down API Manager...
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
ERROR:root:No json object could be decoded from data: b'missing version key'
INFO:root:Shutting down Tribler

```

**Comment by ichorid** [comment]
Left Tribler running for the night, in the morning got this:
```python
[PID:27702] 2020-03-06 11:16:38,943 - ERROR <session:370> Session.unhandled_error_observer(): Got unhandled error: [Errno -2] Name or service not known
  File "/home/vader/src/TRIBLER/py37venv2/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/home/vader/src/TRIBLER/py37venv2/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 784, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
[PID:27643] 2020-03-06 11:16:38,965 - ERROR <tribler_window:102> root.on_exception(): Traceback (most recent call last):
  File "/home/vader/src/TRIBLER/Tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 114, in on_read_data
    raise RuntimeError(json_dict["event"]["text"])
RuntimeError: [Errno -2] Name or service not known
```

**Comment by Dmole** [comment]
This happened again.
There is no option to copy-paste all (Linux)
bug report still won't send.
Screen shot attached;
![fail](https://user-images.githubusercontent.com/1793802/76171933-f993e880-6166-11ea-8577-efd144d4602b.png)

**Comment by ichorid** [comment]
The actual problem is solved in #5194. The problem with not being able to send the report was already fixed in 7.5.0-exp2. @Dmole , from your report I see that you're still using 7.5.0-exp1. Please, upgrade to 7.5.0-exp2 to be able to send tracebacks.

**Comment by Dmole** [comment]
@ichorid I'll have to wait for exp3;
https://github.com/Tribler/tribler/issues/5192

**Comment by ichorid** [comment]
Deployment test machine sent this for 7.5.0-exp4:
```python
Traceback (most recent call last):
File "/home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 114, in on_read_data
RuntimeError: Traceback (most recent call last):
File "/usr/lib/python3.6/asyncio/events.py", line 145, in _run
File "ipv8/taskmanager.py", line 107, in done_cb
File "ipv8/messaging/anonymization/tunnel.py", line 166, in resolve
File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
socket.gaierror: [Errno -2] Name or service not known
```

@egbertbouman , could you please look at this?

**Comment by ichorid** [comment]
Well, that's a little embarrassing to say, but the problem is still there in 7.5.0-rc1 according to Reporter...

**Comment by egbertbouman** [comment]
I can't seem to find the crash report you're referring to. Or are you referring to errno 11001/11004 (which are different exceptions)?

We've already added some code to prevent crashing on that error (https://github.com/Tribler/tribler/blob/devel/src/tribler-core/tribler_core/session.py#L337), yet is still happens. That seems to be because the exception type is missing from the string that we're checking.

**Comment by ichorid** [comment]
Yep, I'm talking about 11001/11004.
[These](http://reporter.tribler.org/stacktrace/32196) [two](http://reporter.tribler.org/stacktrace/32198) reports.

**Comment by ichorid** [comment]
`socket.gaierror: [Errno -2] Name or service not known` error [report](http://reporter.tribler.org/stacktrace/32249)

**Comment by ichorid** [comment]
When I `raise` an `Exception`, its `text` in `unhandled_errors_observer` does not include the error type, thus text-based ignored-error-catchers like ` if 'builtins.OSError' in text and '[Errno 113]' in text:` do not trigger.

The corresponding `test_error_observer_ignored_error` does not really test anything, because of it not using real `raise` calls. Instead, it checks reactions to dummy `dict`s.

**Comment by ichorid** [comment]
I'm handling this properly now...

**Comment by Dmole** [comment]
Good because [7.5.0-exp1] is still crashing in under 12h with
```
Traceback (most recent call last):
  File "/home/tribler/jenkins/workspace/Build-Tribler_release/Async-Py3-Build-Ubuntu64/tribler/src/tribler-gui/tribler_gui/event_request_manager.py", line 114, in on_read_data
RuntimeError: Task was destroyed but it is pending!
```

**Comment by ichorid** [comment]
@Dmole , that's a [completely different error ](https://github.com/Tribler/tribler/issues/5220)

**Comment by Dmole** [comment]
It did not show up in my search;

https://github.com/Tribler/tribler/issues?q=is%3Aissue+is%3Aopen+7.5.0-exp1+event_request_manager.py

and I assumed there may be an underlying iesue in event_request_manager.py causing one line stack traces.

**Comment by ichorid** [comment]
"one-line stack traces" you're talking about [are already fixed](https://github.com/Tribler/tribler/pull/5236) :wink:

**Comment by Dmole** [comment]
With those 2 things fixed it's a good time for rc2 IMO. (this issue is less intrusive than the others)

**Comment by ichorid** [comment]
Fixed in #5224
