### ISSUE TITLE
test_channel_update_and_download fails randomly

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5454]
For instance:
https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_linux/767/testReport/junit/test_channel_download/TestChannelDownload/test_channel_update_and_download/

**Comment by qstokkink** [comment]
Quick question about the tagging: what kind of response should the team give to "Needs triage"?

Do you want to foster discussion on whether or not the bug should be fixed and in what milestone? Or, should we see this more as a "pending" tag and the bug just needs to eventually be fixed?

**Comment by ichorid** [comment]
@qstokkink , I'm playing around to see which way of organizing the issues fits our repo the best. So don't pay heed to it, at least for a couple of days.

**Comment by devos50** [comment]
@ichorid let us know if you need feedback on these organisational matters!

**Comment by devos50** [comment]
Any update on this issue? It seems to fail on `devel` currently, see [here](https://jenkins-ci.tribler.org/job/Test_tribler_devel/102/testReport/junit/test_channel_download/TestChannelDownload/test_channel_update_and_download/).

**Comment by devos50** [comment]
This still fails on devel, see for example [here](https://jenkins-ci.tribler.org/job/GH_Tribler_PR_Tests/job/PR_linux_pytest/120/).

```
>           assert channel2.timestamp == channel2.local_version
E           assert 1565621688018 == 1565621688015
E             +1565621688018
E             -1565621688015
```

**Comment by devos50** [comment]
@ichorid can you have another look at this?

**Comment by devos50** [comment]
Actually, I might have been a bit too quick with re-opening this issue. I noticed that this error happens in https://github.com/Tribler/tribler/pull/5619 but a retest also fails. So, this issue is most likely caused by the PR itself. 👍
