### ISSUE TITLE
8.1.0 prerelease used 59gb of memory

### ISSUE THREAD

**Issue by balupton** [Tribler/tribler#8485]
After upgrading to the 8.1.0 prerelease from 8.0.7 on a m1 Mac mini running the latest macOS resulted in the force quit out of memory macOS modal after about an hour of use, in which tribler was the culprit at 59gb of memory on a 16gb of ram machine. I had to force quit it from that modal as the menu bar icon was unresponsive.

I have I guess 200 torrents in which half of them are completed.

Haven't reopened it since the force quit.

Let me know what steps are needed to send the logs.

**Comment by teddyrogers** [comment]
I have noticed this on Windows too. Last time I check Tribler was using 5.8GB.

**Comment by absolutep** [comment]
> After upgrading to the 8.1.0 prerelease from 8.0.7 on a m1 Mac mini running the latest macOS resulted in the force quit out of memory macOS modal after about an hour of use, in which tribler was the culprit at 59gb of memory on a 16gb of ram machine. I had to force quit it from that modal as the menu bar icon was unresponsive.
> 
> I have I guess 200 torrents in which half of them are completed.
> 
> Haven't reopened it since the force quit.
> 
> Let me know what steps are needed to send the logs.

**Did you change Hops?**

This happened with me [sudden rise in size of Tribler folder] also.

I changed Hops of my torrents and then suddenly my Tribler folder was equivalent to 80 GB.

All these torrents of mine, were already present in BiglyBT, so when I opened BiglyBT - all those torrents suffered disk error & automatically deleted themselves.

I have put them on redownload but some torrents were very obscure - hopefully I can get them back.

**Comment by teddyrogers** [comment]
I think my issue may have been related to the debug logs. When the logs are open it is consuming excessive amounts of memory in the browser, not specific to the Tribler process. I have seen it use up to over 8GB of memory.

**Comment by balupton** [comment]
No change in hops, they have all been 3 hops.

I did not have the web client open at the time.

**Comment by teddyrogers** [comment]
I checked Tribler process today and it is reporting 7.2GB....

![Image](https://github.com/user-attachments/assets/c370142c-4d03-421e-9062-29e3e1df6349)

Unfortunately I restarted Tribler before checking where the memory is being used.

**Comment by mouse-the** [comment]
Since upgrading to 8.1.0 I am also seeing uncontrolled memory usage. 
Debian Linux, 24g ram, 1g swap. Github .deb 8.1.0
I do have a 3 digit number of downloads, all but ~10 completed.
This morning I managed to observe something that probably also happened twice yesterday.
In short, after running unattended for 6 hours, tribler had used all the memory.
kswapd was running the CPU hard, 
tribler had more than half the ram and 60g of virt
I think the KDE lockscreen did not manage to come up until tribler shut down.

I have tribler's output redirected to /dev/null to prevent it from filling my root partition, so I have not been able to look for hints there.

Based on casually observing top while writing this, tribler seems to be steadily consuming memory, maybe on the order of a gig per hour. ...and already 42g of virt...

Oh, poking around in the journal confirms the kernel killed tribler:
`Mar 09 03:03:21 mouse23 systemd[1139]: Started app-org.tribler.Tribler-4cd2900cefb443c68466c7f5074053ed.scope - Tribler - P2P /Bittorrent/Youtube client.
Mar 09 11:37:19 mouse23 kernel: [  25337]  1000 25337 15914039  3590121 35635200     5895           200 tribler
Mar 09 11:37:19 mouse23 kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service/app.slice/app-org.tribler.Tribler-4cd2900cefb443c68466c7f5074053ed.scope,task=tribler,pid=25337,uid=1000
Mar 09 11:37:19 mouse23 kernel: Out of memory: Killed process 25337 (tribler) total-vm:63656156kB, anon-rss:14360476kB, file-rss:0kB, shmem-rss:8kB, UID:1000 pgtables:34800kB oom_score_adj:200
Mar 09 11:37:18 mouse23 systemd[1139]: app-org.tribler.Tribler-4cd2900cefb443c68466c7f5074053ed.scope: A process of this unit has been killed by the OOM killer.
Mar 09 11:37:20 mouse23 kernel: oom_reaper: reaped process 25337 (tribler), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
Mar 09 11:37:20 mouse23 systemd[1139]: app-org.tribler.Tribler-4cd2900cefb443c68466c7f5074053ed.scope: Failed with result 'oom-kill'.
Mar 09 11:37:20 mouse23 systemd[1139]: app-org.tribler.Tribler-4cd2900cefb443c68466c7f5074053ed.scope: Consumed 4h 32min 11.684s CPU time.
`

...and another glance at top suggests that the memory has leveled off for now...
Let me know if I can help.

**Comment by teddyrogers** [comment]
Logged on today, checked Task Manager and Tribler was using 11.5GB memory. Took a screenshot...

![Image](https://github.com/user-attachments/assets/772631e4-6188-4fc3-affe-10c3a2ca562d)

...then went to check process memory usage to diagnose and it dropped back down to 1.2GB???

**Comment by qstokkink** [comment]
Thanks for the input everyone. I think we hit this bug (inside our `libtorrent` dependency, which has been updated to support Bittorrent v2): https://github.com/arvidn/libtorrent/issues/6667

If I read that (massive) issue correctly, the default disk writing mode of `mmap` is causing these issues. We [should be able to](https://www.libtorrent.org/reference-Settings.html) fix this in Tribler by setting the default disk writing mode (`disk_write_mode`) to `mmap_write_mode_t.always_pwrite`. We'll try that for the next pre-release.

**Comment by qstokkink** [comment]
@HanabishiRecca thanks for the help! Setting the `mmap_file_size_cutoff` to the max int was not quite obvious to me from the docs. I imagine that took quite a bit of effort to find.

_Re-opening this issue until the above is implemented._

**Comment by teddyrogers** [comment]
Tribler 8.1.1, there is a large amount of memory pages being allocated for torrent data files. I believe this to be a continuation of https://github.com/Tribler/tribler/issues/8485.

A current Tribler session is using 8.95GB of memory...

![Image](https://github.com/user-attachments/assets/ef961af3-c5e4-4aa9-a155-05e9a73fa49c)

...here are the commits to Triblers memory map...

![Image](https://github.com/user-attachments/assets/ef46b766-3f07-4ed7-864d-08a72d48cd58)

**Comment by teddyrogers** [comment]
@qstokkink Tribler 8.1.2, whilst not as savage as previous 8.1.x releases memory usage is still a problem.

![Image](https://github.com/user-attachments/assets/f8b4ea8f-7c13-47ff-9a50-5ed392768a47)

Do you require further information to resolve?

**Comment by balupton** [comment]
just stating in advance that I (the OP) won't be available to test or feedback anything until end of april, so feel fee to close or reopen if it is a peovlem

**Comment by qstokkink** [comment]
Unless @HanabishiRecca has any more magic settings for us to play with, I think this is just the cost of supporting v2 torrents. So, regarding:

> Do you require further information to resolve?

I think that - at this point - we cannot resolve this and the only way we can further reduce memory, is by going back to BitTorrent v1 again. This is probably also the reason why qBittorrent offers a v1 and v2 option.

**Comment by HanabishiRecca** [comment]
`mmap_file_size_cutoff` mitigates the mmap problem. E.g. my server instance (qbittorrent-nox) never goes beyond even 100M.

So I see only 2 reaons:
1. The setting is not applied for some reason.
2. This is another unrelated memory leak.

**Comment by qstokkink** [comment]
That is useful input! Tribler didn't have this memory consumption before: if it is possible to not go over 100M, we must still have a chance to reduce memory consumption. In turn, if there is still a chance to reduce memory usage, I'll keep this issue open.

**Comment by HanabishiRecca** [comment]
> I think this is just the cost of supporting v2 torrents.

Btw about that. Libtorrent 1.x is effectively unmaintained and at this point doesn't even compile against the last version of Boost (arvidn/libtorrent#7796). So it's only matter of time when it would became completely unusable.

**Comment by HanabishiRecca** [comment]
I also noticed that Tribler [uses](https://github.com/Tribler/tribler/blob/fd0593f96981538d5fe7ecdfe974dec70692632f/requirements.txt#L6) an outdated version of libtorrent (2.0.9). It is highly advised to upgrade to the latest (2.0.11 atm) as we also pushed a lot of fixes on its side in conjunction.

**Comment by mouse-the** [comment]
I seem to have stumbled across something interesting. Instead of redirecting all output to /dev/null I passed --log-level=WARNING and my memory consumption went way down. It looks like WARNING, ERROR and CRITICAL are all much better than the default of INFO. 
I ran 8.1.2 overnight at CRITICAL with my big ~/.Tribler/ and RSS growth averaged 190k per minute instead of 25m.

A git version from a week ago seems to behave the  same. 
I was playing around with heaptrack, but I do not think it ever saw the problem. ...and I did not really know what I was doing.
(Because @HanabishiRecca mentioned it I will report that I have been using libtorrent 2.0.11 for a week with no obvious problems.)

Let me if I can help by poking at anything here.

**Comment by qstokkink** [comment]
> It looks like WARNING, ERROR and CRITICAL are all much better than the default of INFO.

Thanks for sharing. I made a mistake in the implementation here. I apprently misread the Python documentation. I was convinced that the memory buffer was in bytes, so I thought I was storing the last 100000 bytes (0.1 MB) of logging output:

https://github.com/Tribler/tribler/blob/4c8752b96ce95a52f4573599665ee7c3222d3383/src/tribler/core/restapi/logging_endpoint.py#L24

I double-checked myself and this `100000` number is actually [defined as](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.BufferingHandler) `the number of logging records buffered`. With every record probably being in the order of a few hundred characters, let's say 200, this would bump up the memory use to 20 MB, instead of the intended 0.1 MB. Nowhere near the reported gigabytes of memory use, but still unintended.

> I have been using libtorrent 2.0.11 for a week with no obvious problems.

That is good to hear. This is planned for our next (8.2) release. It would be nice if that fixes this memory issue.

**Comment by mouse-the** [comment]
> That is good to hear. This is planned for our next (8.2) release. It would be nice if that fixes this memory issue.

To be clear: I did not notice any additional problems from using libtorrent 2.0.11. I still have the same memory use problems that seem to be caused by the logging endpoint.

**Comment by qstokkink** [comment]
Interesting, that would point to some sort of memory leak inside the Python interpreter itself: we're just using stock Python logging functionality.

I'll try to comb through the CPython source code when I have some time (memo for myself: [source code pointer](https://github.com/python/cpython/blob/3.10/Lib/logging/handlers.py#L1333)).

**Comment by qstokkink** [comment]
I ran a test with our logging setup, but I set the `MemoryHandler`'s `capacity` to `1`. This means that the buffer size should be one record. To my suprise, however, the `MemoryHandler.buffer` was never cleared. It just kept on growing.

This left me somewhat confused, but diving deeper into the Python source showed me this:

```python
    def flush(self):
        """
        For a MemoryHandler, flushing means just sending the buffered
        records to the target, if there is one. Override if you want
        different behaviour.

        The record buffer is also cleared by this operation.
        """
        self.acquire()
        try:
            if self.target:
                for record in self.buffer:
                    self.target.handle(record)
                self.buffer.clear()
        finally:
            self.release()
```

Essentially, Python's implementation **disregards the buffer capacity completely AND**, if there is no downstream `target` set in the logging handler hierarchy, **causes a memory leak**. For posterity, I will note this as the most silly buffer capacity implementation I have ever seen. For now, I know what to fix though, on our side.

**Comment by mouse-the** [comment]
I pulled down the new code, and my memory problems seem to be fixed. Thanks for digging into this one!
